[tool.black]
line-length = 90

[tool.pylint]
max-line-length = 100
disable = ["W0511"]

[mypy]
disallow_untyped_defs = true

# --- Defaults ---
# strict_optional = true      # we had off
# warn_return_any = true      # we had off
# show_none_errors = true
# incremental = true
# allow_redefinition = false   # we had on

strict = true
# --- Flags that get enabled by strict ---
# warn_unused_configs = true
# disallow_any_generics = true
# disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_incomplete_defs = true
# check_untyped_defs = true
# disallow_untyped_decorators = true
# no_implicit_optional = true
# warn_redundant_casts = true
warn_return_any = true
# implicit_reexport = true
# strict_equality = true

